In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
from matplotlib import pyplot as plt

In [23]:
df=pd.read_csv(r'C:\Users\anil\Downloads\py-master\py-master\ML\2_linear_reg_multivariate\homeprices.csv')

In [24]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
median=df.bedrooms.median()
median

4.0

In [26]:
df.fillna(median,inplace=True)

In [27]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [28]:
reg=linear_model.LinearRegression()

In [30]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [32]:
reg.intercept_

221323.00186540408

In [38]:
reg.predict([[3000,4,15]])

array([602590.07937407])

In [63]:
df1=pd.read_csv(r'C:\Users\anil\Downloads\py-master\py-master\ML\2_linear_reg_multivariate\Exercise\hiring.csv')

In [40]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [42]:
from word2number import w2n
reg1=linear_model.LinearRegression()

In [64]:
df1['test_score(out of 10)'].fillna(df1['test_score(out of 10)'].median(),inplace=True)

In [77]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [67]:
df1.experience.fillna('zero',inplace=True)

In [68]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [76]:
df1.experience = df1.experience.apply(w2n.word_to_num)

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [80]:
reg1.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [83]:
reg1.predict([[12,10,10]])

array([92002.18340611])